name: linux

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        rust_toolchain: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
    - name: Install Rust
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        profile: minimal
        toolchain: ${{ matrix.rust_toolchain }}
    - name: Build and test
      run: |
        rustc -V
        cargo -V
        cargo build
        tests/run_integration_tests.sh
        rustdoc --test README.md -L target
        cargo run --manifest-path systest/Cargo.toml
